baseURL = "https://codewithgamez.github.io/website/"
languageCode = "en-us"
title = "CodeWithGamez"
theme = "hugo-theme-learn"
publishDir = "../docs"
[params]
    showVisitedLinks = true
    themeVariant = "blue"
    
[outputs]
home = [ "HTML", "RSS", "JSON"]


